### ISSUE TITLE
Clicking on "WholePull SD graphs" causes error

### ISSUE THREAD

**Issue by jaa46** [12bell-ringingmodels/rwp-model#14]
Clicking on the "WholePull SD graphs" button gets the following error on the line starting `ActiveChart.SetSourceData Source:=Sheets(TeamName(team) + " 2").Range(alpha((NumBells(team) * 2) + 4)` in the submethod `graph_wholepullsd()`.
(using Excel 2013)

![image](https://cloud.githubusercontent.com/assets/4086519/9390127/286e95b6-4767-11e5-835b-ccd22830f7d3.png)

**Comment by jaa46** [comment]
As does Speed Graphs in graph_speed(), and Bell Analysis in calcWasSuspended().

**Comment by drichards2** [comment]
Works for me in Excel 2007 - will try some other versions.

**Comment by drichards2** [comment]
I've had an idea on this. When you get to the fault condition, are there
two copies of the RodModel2 .bas file present? I can see how that would
lead to that error - check whether there is a module called RodModel21 in
the VBA project.

If it is this type of failure then there are obviously a couple of
workarounds, but I can't help feeling it is related to the broader issues
around the workflow for the spreadsheet.

**Comment by drichards2** [comment]
This was only an issue on the branch for jaa46 - fixed in commit d956b0b94a10473146ca83e7cff1122c3717e683
